spring.application.name=pedidos-service

# H2 Database
spring.datasource.url=jdbc:h2:mem:pedidos_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicialización de schema SQL
spring.sql.init.mode=always

# Puerto
server.port=8080

# Campaña Black Friday (usada en la Parte 2)
promo.black-friday.activa=true
